const ERROR_CODE = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const CREATE_STATUS = 201;
const DUPLICATE_EMAIL = 11000;

module.exports = {
  ERROR_CODE,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  CREATE_STATUS,
  DUPLICATE_EMAIL,
};
